export const SUCCESS_CODES = {
  EDIT_SUCCESSFULLY: 200,
  DELETE_SUCCESSFULLY: 204,
  CREATE_SUCCESSFULLY: 200,
};

export const SUCCESS_MESSAGES = {
  [SUCCESS_CODES.EDIT_SUCCESSFULLY]: 'Edit Successfully',
  [SUCCESS_CODES.DELETE_SUCCESSFULLY]: 'Delete Successfully',
  [SUCCESS_CODES.CREATE_SUCCESSFULLY]: 'Create Successfully',
  DEFAULT: 'Internal Server Error',
};
